image:
  file: .gitpod.Dockerfile


tasks:
  - init: |
      npm install -g create-react-app
#      cd web && npm install
  - command: |
      cd web && npm start
      
#   - name: Static Server
#     command: python3 -m http.server 8080
#   - name: DB Server
#     command: sh ./scripts/start-db.sh
#     openMode: split-right

